# my-project/ansible/inventories/setup.yml
all:
  vars:
    ansible_user: admin
    ansible_ssh_private_key_file: /root/devops-livecoding/id_rsa
  children:
    prod:
      hosts:
       michelfranck.dibangoenga.takima.cloud: {}
